import './js/block-categories';
import './js/header';
import './js/hero';
import './js/list-of-popular';
import './js/list-of-recipes';
import './js/modal-order';
import './js/modal-rating';
import './js/modal-recipe'
import './js/favorite-page'
import './js/API/order-post'