import './js/block-categories.js';
import './js/hero-cook.js';
import './js/request-cook.js';
import './js/header.js';
import './js/hero.js';
import './js/list-of-popular.js';
import './js/list-of-recipes.js';
import './js/modal-order.js';
import './js/modal-rating.js';
import './js/modal-recipe.js'
import './js/favorite-page.js'
import './js/API/order-post.js'
import './js/switcher.js';
import './js/pagination.js'
